server:
  port: 8080

spring:
  application:
    name: Api-Gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000

      routes:
        - id: user_service_auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: user_service_profile
          uri: lb://USER-SERVICE
          predicates:
            - Path=/profile/**

        - id: wallet_service
          uri: lb://WALLET-SERVICE
          predicates:
              - Path=/wallet/**

        - id: transaction_service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**

        - id: savings_service
          uri: lb://SAVINGS-SERVICE
          predicates:
            - Path=/savings/**

        - id: notifications_service
          uri: lb://NOTIFICATIONS-SERVICE
          predicates:
            - Path=/notifications/**

        - id: loans_service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loans/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: false
    fetch-registry: false

  instance:
    preferIpAddress: true