spring:
  application:
    name: Transaction-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/transactions_db
    username: root_user
    password: "@rootuser"
    driverClassName: org.postgresql.Driver

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true