spring:
  application:
    name: Notifications-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/notifications_db
    username: root_user
    password: rootuser
    driverClassName: org.postgresql.Driver

  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Flyway configuration
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

  # Thymeleaf configuration
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true

brevo:
  api:
    key: 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

    url: https://api.brevo.com/v3/smtp/email

app:
  email:
    from:
      address: dogovicky05@gmail.com
      name: Easy Pay

  verification:
    expiry-minutes: 15