spring:
  application:
    name: Notifications-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/notifications_db
    username: root_user
    password: rootuser
    driverClassName: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true