spring:
  application:
    name: User-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: root_user
    password: rootuser
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    exchanges:
      emailSignup: x.signup
      emailLogin: x.login
    queues:
      emailSignup: q.email.signup
      smsSignup: q.sms.signup
      smsLogin: q.sms.login # OTP verification for 2-step verification
    routing-keys:
      emailSignup: user.signup.email
      smsSignup: user.signup.sms
      smsLogin: user.login.sms


  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

  jpa:
    hibernate:
     ddl-auto: none

  redis:
    # Connection Details
    host: localhost
    port: 6379

    # Authentication details
    username: root_user
    password: rootu$er
    timeout: 60000

    # Connection pool configurations
    lettuce:
      pool:
        max-active: 16 # Maximum number of connections
        max-idle: 8 # Maximum number of idle connections
        min-idle: 4 # Minimum number of idle connections
        max-wait: 2000 # Maximum wait time for a connection



server:
  port: 8086



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true



jwt:
  secret: vOQX5AgOWjtj3OWVPKfRIBfhtcHtQ0mmvBCYJN9/A9bJDuikID4hi8DpnNFzY/C99uxfPhFyMBWpw5POszEIzQ==


logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR